---
# ============================================================================ #
# This is a shared RabbitMQ instance.
# ============================================================================ #
include:
  - network.yml

services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    container_name: rabbitmq
    hostname: rabbitmq01
    labels:
      - application=rabbitmq
    volumes:
      - type: bind
        source: ../volumes/rabbitmq/node01/config
        target: /etc/rabbitmq
      - type: bind
        source: ../volumes/rabbitmq/node01/data
        target: /var/lib/rabbitmq
        consistency: delegated
    ports:
      - "5672:5672" # amqp non-TLS
      - "15672:15672" # management non-TLS
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - appnet
